### ISSUE TITLE
Error when viewing program

### ISSUE THREAD

**Issue by jimanderton** [IEc-NFWF/nfwf-ckan-extensions#1]
1. Click "Programs" on home page
2. Click ECRF program on /group page
3. Internal server error will be displayed on the page between the header and footer. Error from ckan log is below:

**In addition to the error at the bottom of the stack trace, also take note of the various complains about group_\* vs group.\* at the top. This is something that needs to be fixed.**

ckan        | 2023-08-22 16:53:11,637 INFO  [ckan.lib.helpers] Route name "group_index" is deprecated and will be removed. Please update calls to use "group.index" instead
ckan        | 2023-08-22 16:53:11,638 INFO  [ckan.lib.helpers] Route name "group_read" is deprecated and will be removed. Please update calls to use "group.read" instead
ckan        | 2023-08-22 16:53:11,643 INFO  [ckan.lib.helpers] Route name "group_index" is deprecated and will be removed. Please update calls to use "group.index" instead
ckan        | 2023-08-22 16:53:11,648 INFO  [ckan.lib.helpers] Route name "group_read" is deprecated and will be removed. Please update calls to use "group.read" instead
ckan        | 2023-08-22 16:53:11,811 ERROR [ckan.config.middleware.flask_app] not enough values to unpack (expected 2, got 1)
ckan        | Traceback (most recent call last):
ckan        |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
ckan        |     rv = self.dispatch_request()
ckan        |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
ckan        |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ckan        |   File "/srv/app/src/ckan/ckan/config/middleware/../../views/group.py", line 463, in read
ckan        |     return base.render(
ckan        |   File "/srv/app/src/ckan/ckan/lib/base.py", line 107, in render
ckan        |     return flask_render_template(template_name, **extra_vars)
ckan        |   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
ckan        |     return _render(
ckan        |   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
ckan        |     rv = template.render(context)
ckan        |   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
ckan        |     self.environment.handle_exception()
ckan        |   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
ckan        |     raise rewrite_traceback_stack(source=source)
ckan        |   File "/srv/app/src/ckan/ckan/templates/group/read.html", line 2, in top-level template code
ckan        |     {% set dataset_type = h.default_package_type() %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/group/read_base.html", line 1, in top-level template code
ckan        |     {% extends "page.html" %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 1, in top-level template code
ckan        |     {% extends "base.html" %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/base.html", line 1, in top-level template code
ckan        |     {% ckan_extends %}
ckan        |   File "/srv/app/src/ckan/ckan/templates/base.html", line 108, in top-level template code
ckan        |     {%- block page %}{% endblock -%}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 19, in block 'page'
ckan        |     {%- block content %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 22, in block 'content'
ckan        |     {% block main_content %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 74, in block 'main_content'
ckan        |     {% block primary %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 87, in block 'primary'
ckan        |     {% block primary_content %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 89, in block 'primary_content'
ckan        |     {% block page_header %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/page.html", line 97, in block 'page_header'
ckan        |     {% block content_primary_nav %}{% endblock %}
ckan        |   File "/srv/app/ckanext-nfwf_theme/ckanext/nfwf_theme/templates/group/read_base.html", line 17, in block 'content_primary_nav'
ckan        |     {{ h.build_nav_icon(group_type + '_read', _('Datasets'), id=c.group_dict.name) }}
ckan        |   File "/srv/app/src/ckan/ckan/lib/helpers.py", line 879, in build_nav_icon
ckan        |     return _make_menu_item(menu_item, title, **kw)
ckan        |   File "/srv/app/src/ckan/ckan/lib/helpers.py", line 954, in _make_menu_item
ckan        |     controller, action = menu_item.split('.')
ckan        | ValueError: not enough values to unpack (expected 2, got 1)
ckan        | 2023-08-22 16:53:11,889 INFO  [ckan.config.middleware.flask_app]  500 /group/emergency-coastal-resilience-fund render time 0.784 seconds

**Comment by alex-kruger** [comment]
fixed in most recent push by replacing underscores with periods
